[2023-04-25T09:05:33.270+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_on_slack_integration.dummy_task scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-04-25T09:05:33.278+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_on_slack_integration.dummy_task scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-04-25T09:05:33.279+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T09:05:33.280+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-25T09:05:33.280+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T09:05:33.289+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): dummy_task> on 2023-04-24 00:00:00+00:00
[2023-04-25T09:05:33.293+0000] {standard_task_runner.py:55} INFO - Started process 2703 to run task
[2023-04-25T09:05:33.295+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'task_on_slack_integration', 'dummy_task', 'scheduled__2023-04-24T00:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/Task3.py', '--cfg-path', '/tmp/tmp18o5aygy']
[2023-04-25T09:05:33.296+0000] {standard_task_runner.py:83} INFO - Job 128: Subtask dummy_task
[2023-04-25T09:05:33.346+0000] {task_command.py:389} INFO - Running <TaskInstance: task_on_slack_integration.dummy_task scheduled__2023-04-24T00:00:00+00:00 [running]> on host d51842477fac
[2023-04-25T09:05:33.394+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=task_on_slack_integration
AIRFLOW_CTX_TASK_ID=dummy_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-24T00:00:00+00:00
[2023-04-25T09:05:33.396+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Task3.py", line 12, in _random_fail
    raise Exception("number less than 50, so fail")
Exception: number less than 50, so fail
[2023-04-25T09:05:33.404+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=task_on_slack_integration, task_id=dummy_task, execution_date=20230424T000000, start_date=20230425T090533, end_date=20230425T090533
[2023-04-25T09:05:33.411+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 128 for task dummy_task (number less than 50, so fail; 2703)
[2023-04-25T09:05:33.428+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-25T09:05:33.447+0000] {taskinstance.py:2596} INFO - 1 downstream tasks scheduled from follow-on schedule check
